### ISSUE TITLE
统一社会信用代码校验

### ISSUE THREAD

**Issue by jw-star** [landlordxu/generator#2]
统一社会信用代码校验，校验存在问题

例如： 12440600MB2C07549J

`

import java.util.HashMap;
import java.util.Map;

public class HelloWorld {
    public static void main(String []args) {
        HelloWorld helloWorld = new HelloWorld();

        boolean b = helloWorld.validate18("12440600MB2C07549J");
        System.out.println(b);
    }

    public boolean validate18(String bizNo) {

        String regex = "^([0-9ABCDEFGHJKLMNPQRTUWXY]{2})([0-9]{6})([0-9ABCDEFGHJKLMNPQRTUWXY]{10})$";
        if (!bizNo.matches(regex)) {
            return false;
        }

        String baseCode = "0123456789ABCDEFGHJKLMNPQRTUWXY";
        char[] baseCodeArray = baseCode.toCharArray();
        Map<Character, Integer> codes = new HashMap<Character, Integer>();
        for (int i = 0; i < baseCode.length(); i++) {
            codes.put(baseCodeArray[i], i);
        }

        char[] businessCodeArray = bizNo.toCharArray();
        Character check = businessCodeArray[17];
        if (baseCode.indexOf(check) == -1) {
            return false;
        }

        int[] ws = { 1, 3, 9, 27, 19, 26, 16, 17, 20, 29, 25, 13, 8, 24, 10, 30, 28 };
        int sum = 0;
        for (int i = 0; i < 17; i++) {
            Character key = businessCodeArray[i];
            if (baseCode.indexOf(key) == -1) {
                return false;
            }
            sum += (codes.get(key) * ws[i]);
        }

        int c18 = 31 - sum % 31;
        if (c18 == 31) {
            c18 = 0;
        }
        return c18 == codes.get(check);

    }
}

`

**Comment by xbeginagain** [comment]
12440600MB2C07549J 这个统一信用代码校验方法是通过的，你这段代码是自己写的Java代码，不是用js验证代码验证的吧。

**Comment by jw-star** [comment]
> 12440600MB2C07549J 这个统一信用代码校验方法是通过的，你这段代码是自己写的Java代码，不是用js验证代码验证的吧。

对的，java的是网上的工具类，我另外还找了一个工具类，都测试了，有些统一社会信用代码校验确实有问题
