### ISSUE TITLE
统一社会信用代码校验写错了

### ISSUE THREAD

**Issue by Xpecya** [landlordxu/generator#3]
var str = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  var wi =[1,3,9,27,19,26,16,17,20,29,25,13,8,24,10,30,28];
	var sum = 0;
    for (var i = 0; i < 17; i++) {
      sum += str.indexOf(creditCode.charAt(i)) * wi[i];
  }

str里面不能有I O Z S V

**Comment by xbeginagain** [comment]
确实是不能有I O Z S V，已修改。
